s = set()

n = int(input('number 1: '))
s.add(int(n))
n = int(input('number 2: '))
s.add(int(n))
n = int(input('number 3: '))
s.add(int(n))
n = int(input('number 4: '))
s.add(int(n))
n = int(input('number 5: '))
s.add(int(n))
n = int(input('number 6: '))
s.add(int(n))
n = int(input('number 7: '))
s.add(int(n))
n = int(input('number 8: '))
s.add(int(n))

print(s)

